# GitHub Sponsor button configuration for OpenCode Starter
# Created by andiupn — kuncimu.com

ko_fi: andiupn
patreon: AndiUpn
custom:
  - https://trakteer.id/andi_upn
  - https://saweria.co/andiupn
  - https://kuncimu.com
